// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: client_messages.proto
#ifndef GRPC_client_5fmessages_2eproto__INCLUDED
#define GRPC_client_5fmessages_2eproto__INCLUDED

#include "client_messages.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace client_messages {

class ClientMessages final {
 public:
  static constexpr char const* service_full_name() {
    return "client_messages.ClientMessages";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status HandleClient(::grpc::ClientContext* context, const ::client_messages::HandleClientRequest& request, ::client_messages::HandleClientResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::client_messages::HandleClientResponse>> AsyncHandleClient(::grpc::ClientContext* context, const ::client_messages::HandleClientRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::client_messages::HandleClientResponse>>(AsyncHandleClientRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::client_messages::HandleClientResponse>> PrepareAsyncHandleClient(::grpc::ClientContext* context, const ::client_messages::HandleClientRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::client_messages::HandleClientResponse>>(PrepareAsyncHandleClientRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void HandleClient(::grpc::ClientContext* context, const ::client_messages::HandleClientRequest* request, ::client_messages::HandleClientResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void HandleClient(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::client_messages::HandleClientResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void HandleClient(::grpc::ClientContext* context, const ::client_messages::HandleClientRequest* request, ::client_messages::HandleClientResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void HandleClient(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::client_messages::HandleClientResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::client_messages::HandleClientResponse>* AsyncHandleClientRaw(::grpc::ClientContext* context, const ::client_messages::HandleClientRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::client_messages::HandleClientResponse>* PrepareAsyncHandleClientRaw(::grpc::ClientContext* context, const ::client_messages::HandleClientRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status HandleClient(::grpc::ClientContext* context, const ::client_messages::HandleClientRequest& request, ::client_messages::HandleClientResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::client_messages::HandleClientResponse>> AsyncHandleClient(::grpc::ClientContext* context, const ::client_messages::HandleClientRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::client_messages::HandleClientResponse>>(AsyncHandleClientRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::client_messages::HandleClientResponse>> PrepareAsyncHandleClient(::grpc::ClientContext* context, const ::client_messages::HandleClientRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::client_messages::HandleClientResponse>>(PrepareAsyncHandleClientRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void HandleClient(::grpc::ClientContext* context, const ::client_messages::HandleClientRequest* request, ::client_messages::HandleClientResponse* response, std::function<void(::grpc::Status)>) override;
      void HandleClient(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::client_messages::HandleClientResponse* response, std::function<void(::grpc::Status)>) override;
      void HandleClient(::grpc::ClientContext* context, const ::client_messages::HandleClientRequest* request, ::client_messages::HandleClientResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void HandleClient(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::client_messages::HandleClientResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::client_messages::HandleClientResponse>* AsyncHandleClientRaw(::grpc::ClientContext* context, const ::client_messages::HandleClientRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::client_messages::HandleClientResponse>* PrepareAsyncHandleClientRaw(::grpc::ClientContext* context, const ::client_messages::HandleClientRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_HandleClient_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status HandleClient(::grpc::ServerContext* context, const ::client_messages::HandleClientRequest* request, ::client_messages::HandleClientResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_HandleClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_HandleClient() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_HandleClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HandleClient(::grpc::ServerContext* context, const ::client_messages::HandleClientRequest* request, ::client_messages::HandleClientResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHandleClient(::grpc::ServerContext* context, ::client_messages::HandleClientRequest* request, ::grpc::ServerAsyncResponseWriter< ::client_messages::HandleClientResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_HandleClient<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_HandleClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_HandleClient() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::client_messages::HandleClientRequest, ::client_messages::HandleClientResponse>(
          [this](::grpc::ServerContext* context,
                 const ::client_messages::HandleClientRequest* request,
                 ::client_messages::HandleClientResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->HandleClient(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_HandleClient(
        ::grpc::experimental::MessageAllocator< ::client_messages::HandleClientRequest, ::client_messages::HandleClientResponse>* allocator) {
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::client_messages::HandleClientRequest, ::client_messages::HandleClientResponse>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_HandleClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HandleClient(::grpc::ServerContext* context, const ::client_messages::HandleClientRequest* request, ::client_messages::HandleClientResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void HandleClient(::grpc::ServerContext* context, const ::client_messages::HandleClientRequest* request, ::client_messages::HandleClientResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_HandleClient<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_HandleClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_HandleClient() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_HandleClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HandleClient(::grpc::ServerContext* context, const ::client_messages::HandleClientRequest* request, ::client_messages::HandleClientResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_HandleClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_HandleClient() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_HandleClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HandleClient(::grpc::ServerContext* context, const ::client_messages::HandleClientRequest* request, ::client_messages::HandleClientResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHandleClient(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_HandleClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_HandleClient() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->HandleClient(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_HandleClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HandleClient(::grpc::ServerContext* context, const ::client_messages::HandleClientRequest* request, ::client_messages::HandleClientResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void HandleClient(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_HandleClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_HandleClient() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::client_messages::HandleClientRequest, ::client_messages::HandleClientResponse>(std::bind(&WithStreamedUnaryMethod_HandleClient<BaseClass>::StreamedHandleClient, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_HandleClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status HandleClient(::grpc::ServerContext* context, const ::client_messages::HandleClientRequest* request, ::client_messages::HandleClientResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHandleClient(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::client_messages::HandleClientRequest,::client_messages::HandleClientResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_HandleClient<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_HandleClient<Service > StreamedService;
};

}  // namespace client_messages


#endif  // GRPC_client_5fmessages_2eproto__INCLUDED
