// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: raft_messages.proto
#ifndef GRPC_raft_5fmessages_2eproto__INCLUDED
#define GRPC_raft_5fmessages_2eproto__INCLUDED

#include "raft_messages.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace raft_messages {

class RaftMessages final {
 public:
  static constexpr char const* service_full_name() {
    return "raft_messages.RaftMessages";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::raft_messages::RequestVoteResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::RequestVoteResponse>> AsyncRequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::RequestVoteResponse>>(AsyncRequestVoteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::RequestVoteResponse>> PrepareAsyncRequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::RequestVoteResponse>>(PrepareAsyncRequestVoteRaw(context, request, cq));
    }
    virtual ::grpc::Status AppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::raft_messages::AppendEntriesResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::AppendEntriesResponse>> AsyncAppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::AppendEntriesResponse>>(AsyncAppendEntriesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::AppendEntriesResponse>> PrepareAsyncAppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::AppendEntriesResponse>>(PrepareAsyncAppendEntriesRaw(context, request, cq));
    }
    virtual ::grpc::Status InstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::raft_messages::InstallSnapshotResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::InstallSnapshotResponse>> AsyncInstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::InstallSnapshotResponse>>(AsyncInstallSnapshotRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::InstallSnapshotResponse>> PrepareAsyncInstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::InstallSnapshotResponse>>(PrepareAsyncInstallSnapshotRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void RequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest* request, ::raft_messages::RequestVoteResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RequestVote(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raft_messages::RequestVoteResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest* request, ::raft_messages::RequestVoteResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void RequestVote(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raft_messages::RequestVoteResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void AppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest* request, ::raft_messages::AppendEntriesResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AppendEntries(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raft_messages::AppendEntriesResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest* request, ::raft_messages::AppendEntriesResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void AppendEntries(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raft_messages::AppendEntriesResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void InstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest* request, ::raft_messages::InstallSnapshotResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void InstallSnapshot(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raft_messages::InstallSnapshotResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void InstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest* request, ::raft_messages::InstallSnapshotResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void InstallSnapshot(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raft_messages::InstallSnapshotResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::RequestVoteResponse>* AsyncRequestVoteRaw(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::RequestVoteResponse>* PrepareAsyncRequestVoteRaw(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::AppendEntriesResponse>* AsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::AppendEntriesResponse>* PrepareAsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::InstallSnapshotResponse>* AsyncInstallSnapshotRaw(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raft_messages::InstallSnapshotResponse>* PrepareAsyncInstallSnapshotRaw(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status RequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::raft_messages::RequestVoteResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::RequestVoteResponse>> AsyncRequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::RequestVoteResponse>>(AsyncRequestVoteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::RequestVoteResponse>> PrepareAsyncRequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::RequestVoteResponse>>(PrepareAsyncRequestVoteRaw(context, request, cq));
    }
    ::grpc::Status AppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::raft_messages::AppendEntriesResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::AppendEntriesResponse>> AsyncAppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::AppendEntriesResponse>>(AsyncAppendEntriesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::AppendEntriesResponse>> PrepareAsyncAppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::AppendEntriesResponse>>(PrepareAsyncAppendEntriesRaw(context, request, cq));
    }
    ::grpc::Status InstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::raft_messages::InstallSnapshotResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::InstallSnapshotResponse>> AsyncInstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::InstallSnapshotResponse>>(AsyncInstallSnapshotRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::InstallSnapshotResponse>> PrepareAsyncInstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft_messages::InstallSnapshotResponse>>(PrepareAsyncInstallSnapshotRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void RequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest* request, ::raft_messages::RequestVoteResponse* response, std::function<void(::grpc::Status)>) override;
      void RequestVote(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raft_messages::RequestVoteResponse* response, std::function<void(::grpc::Status)>) override;
      void RequestVote(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest* request, ::raft_messages::RequestVoteResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void RequestVote(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raft_messages::RequestVoteResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void AppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest* request, ::raft_messages::AppendEntriesResponse* response, std::function<void(::grpc::Status)>) override;
      void AppendEntries(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raft_messages::AppendEntriesResponse* response, std::function<void(::grpc::Status)>) override;
      void AppendEntries(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest* request, ::raft_messages::AppendEntriesResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void AppendEntries(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raft_messages::AppendEntriesResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void InstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest* request, ::raft_messages::InstallSnapshotResponse* response, std::function<void(::grpc::Status)>) override;
      void InstallSnapshot(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raft_messages::InstallSnapshotResponse* response, std::function<void(::grpc::Status)>) override;
      void InstallSnapshot(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest* request, ::raft_messages::InstallSnapshotResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void InstallSnapshot(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raft_messages::InstallSnapshotResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::raft_messages::RequestVoteResponse>* AsyncRequestVoteRaw(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::raft_messages::RequestVoteResponse>* PrepareAsyncRequestVoteRaw(::grpc::ClientContext* context, const ::raft_messages::RequestVoteRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::raft_messages::AppendEntriesResponse>* AsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::raft_messages::AppendEntriesResponse>* PrepareAsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::raft_messages::AppendEntriesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::raft_messages::InstallSnapshotResponse>* AsyncInstallSnapshotRaw(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::raft_messages::InstallSnapshotResponse>* PrepareAsyncInstallSnapshotRaw(::grpc::ClientContext* context, const ::raft_messages::InstallSnapshotRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RequestVote_;
    const ::grpc::internal::RpcMethod rpcmethod_AppendEntries_;
    const ::grpc::internal::RpcMethod rpcmethod_InstallSnapshot_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RequestVote(::grpc::ServerContext* context, const ::raft_messages::RequestVoteRequest* request, ::raft_messages::RequestVoteResponse* response);
    virtual ::grpc::Status AppendEntries(::grpc::ServerContext* context, const ::raft_messages::AppendEntriesRequest* request, ::raft_messages::AppendEntriesResponse* response);
    virtual ::grpc::Status InstallSnapshot(::grpc::ServerContext* context, const ::raft_messages::InstallSnapshotRequest* request, ::raft_messages::InstallSnapshotResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_RequestVote() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* context, const ::raft_messages::RequestVoteRequest* request, ::raft_messages::RequestVoteResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestVote(::grpc::ServerContext* context, ::raft_messages::RequestVoteRequest* request, ::grpc::ServerAsyncResponseWriter< ::raft_messages::RequestVoteResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_AppendEntries() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* context, const ::raft_messages::AppendEntriesRequest* request, ::raft_messages::AppendEntriesResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAppendEntries(::grpc::ServerContext* context, ::raft_messages::AppendEntriesRequest* request, ::grpc::ServerAsyncResponseWriter< ::raft_messages::AppendEntriesResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* context, const ::raft_messages::InstallSnapshotRequest* request, ::raft_messages::InstallSnapshotResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInstallSnapshot(::grpc::ServerContext* context, ::raft_messages::InstallSnapshotRequest* request, ::grpc::ServerAsyncResponseWriter< ::raft_messages::InstallSnapshotResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RequestVote<WithAsyncMethod_AppendEntries<WithAsyncMethod_InstallSnapshot<Service > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_RequestVote() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>(
          [this](::grpc::ServerContext* context,
                 const ::raft_messages::RequestVoteRequest* request,
                 ::raft_messages::RequestVoteResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->RequestVote(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_RequestVote(
        ::grpc::experimental::MessageAllocator< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>* allocator) {
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* context, const ::raft_messages::RequestVoteRequest* request, ::raft_messages::RequestVoteResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void RequestVote(::grpc::ServerContext* context, const ::raft_messages::RequestVoteRequest* request, ::raft_messages::RequestVoteResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_AppendEntries() {
      ::grpc::Service::experimental().MarkMethodCallback(1,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>(
          [this](::grpc::ServerContext* context,
                 const ::raft_messages::AppendEntriesRequest* request,
                 ::raft_messages::AppendEntriesResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->AppendEntries(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_AppendEntries(
        ::grpc::experimental::MessageAllocator< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>* allocator) {
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>*>(
          ::grpc::Service::experimental().GetHandler(1))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* context, const ::raft_messages::AppendEntriesRequest* request, ::raft_messages::AppendEntriesResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void AppendEntries(::grpc::ServerContext* context, const ::raft_messages::AppendEntriesRequest* request, ::raft_messages::AppendEntriesResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_InstallSnapshot() {
      ::grpc::Service::experimental().MarkMethodCallback(2,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>(
          [this](::grpc::ServerContext* context,
                 const ::raft_messages::InstallSnapshotRequest* request,
                 ::raft_messages::InstallSnapshotResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->InstallSnapshot(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_InstallSnapshot(
        ::grpc::experimental::MessageAllocator< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>* allocator) {
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>*>(
          ::grpc::Service::experimental().GetHandler(2))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* context, const ::raft_messages::InstallSnapshotRequest* request, ::raft_messages::InstallSnapshotResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void InstallSnapshot(::grpc::ServerContext* context, const ::raft_messages::InstallSnapshotRequest* request, ::raft_messages::InstallSnapshotResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_RequestVote<ExperimentalWithCallbackMethod_AppendEntries<ExperimentalWithCallbackMethod_InstallSnapshot<Service > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_RequestVote() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* context, const ::raft_messages::RequestVoteRequest* request, ::raft_messages::RequestVoteResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_AppendEntries() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* context, const ::raft_messages::AppendEntriesRequest* request, ::raft_messages::AppendEntriesResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* context, const ::raft_messages::InstallSnapshotRequest* request, ::raft_messages::InstallSnapshotResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_RequestVote() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* context, const ::raft_messages::RequestVoteRequest* request, ::raft_messages::RequestVoteResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestVote(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_AppendEntries() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* context, const ::raft_messages::AppendEntriesRequest* request, ::raft_messages::AppendEntriesResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAppendEntries(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* context, const ::raft_messages::InstallSnapshotRequest* request, ::raft_messages::InstallSnapshotResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInstallSnapshot(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_RequestVote() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->RequestVote(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* context, const ::raft_messages::RequestVoteRequest* request, ::raft_messages::RequestVoteResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void RequestVote(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_AppendEntries() {
      ::grpc::Service::experimental().MarkMethodRawCallback(1,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->AppendEntries(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* context, const ::raft_messages::AppendEntriesRequest* request, ::raft_messages::AppendEntriesResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void AppendEntries(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_InstallSnapshot() {
      ::grpc::Service::experimental().MarkMethodRawCallback(2,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->InstallSnapshot(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* context, const ::raft_messages::InstallSnapshotRequest* request, ::raft_messages::InstallSnapshotResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void InstallSnapshot(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_RequestVote() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>(std::bind(&WithStreamedUnaryMethod_RequestVote<BaseClass>::StreamedRequestVote, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* context, const ::raft_messages::RequestVoteRequest* request, ::raft_messages::RequestVoteResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRequestVote(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::raft_messages::RequestVoteRequest,::raft_messages::RequestVoteResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_AppendEntries() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>(std::bind(&WithStreamedUnaryMethod_AppendEntries<BaseClass>::StreamedAppendEntries, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* context, const ::raft_messages::AppendEntriesRequest* request, ::raft_messages::AppendEntriesResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAppendEntries(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::raft_messages::AppendEntriesRequest,::raft_messages::AppendEntriesResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>(std::bind(&WithStreamedUnaryMethod_InstallSnapshot<BaseClass>::StreamedInstallSnapshot, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* context, const ::raft_messages::InstallSnapshotRequest* request, ::raft_messages::InstallSnapshotResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedInstallSnapshot(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::raft_messages::InstallSnapshotRequest,::raft_messages::InstallSnapshotResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RequestVote<WithStreamedUnaryMethod_AppendEntries<WithStreamedUnaryMethod_InstallSnapshot<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RequestVote<WithStreamedUnaryMethod_AppendEntries<WithStreamedUnaryMethod_InstallSnapshot<Service > > > StreamedService;
};

class RaftStreamMessages final {
 public:
  static constexpr char const* service_full_name() {
    return "raft_messages.RaftStreamMessages";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>> RequestVote(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>>(RequestVoteRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>> AsyncRequestVote(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>>(AsyncRequestVoteRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>> PrepareAsyncRequestVote(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>>(PrepareAsyncRequestVoteRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>> AppendEntries(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>>(AppendEntriesRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>> AsyncAppendEntries(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>>(AsyncAppendEntriesRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>> PrepareAsyncAppendEntries(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>>(PrepareAsyncAppendEntriesRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>> InstallSnapshot(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>>(InstallSnapshotRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>> AsyncInstallSnapshot(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>>(AsyncInstallSnapshotRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>> PrepareAsyncInstallSnapshot(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>>(PrepareAsyncInstallSnapshotRaw(context, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void RequestVote(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::raft_messages::RequestVoteRequest,::raft_messages::RequestVoteResponse>* reactor) = 0;
      virtual void AppendEntries(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::raft_messages::AppendEntriesRequest,::raft_messages::AppendEntriesResponse>* reactor) = 0;
      virtual void InstallSnapshot(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::raft_messages::InstallSnapshotRequest,::raft_messages::InstallSnapshotResponse>* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>* RequestVoteRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>* AsyncRequestVoteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>* PrepareAsyncRequestVoteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>* AppendEntriesRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>* AsyncAppendEntriesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>* PrepareAsyncAppendEntriesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>* InstallSnapshotRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>* AsyncInstallSnapshotRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>* PrepareAsyncInstallSnapshotRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>> RequestVote(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>>(RequestVoteRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>> AsyncRequestVote(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>>(AsyncRequestVoteRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>> PrepareAsyncRequestVote(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>>(PrepareAsyncRequestVoteRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>> AppendEntries(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>>(AppendEntriesRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>> AsyncAppendEntries(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>>(AsyncAppendEntriesRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>> PrepareAsyncAppendEntries(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>>(PrepareAsyncAppendEntriesRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>> InstallSnapshot(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>>(InstallSnapshotRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>> AsyncInstallSnapshot(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>>(AsyncInstallSnapshotRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>> PrepareAsyncInstallSnapshot(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>>(PrepareAsyncInstallSnapshotRaw(context, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void RequestVote(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::raft_messages::RequestVoteRequest,::raft_messages::RequestVoteResponse>* reactor) override;
      void AppendEntries(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::raft_messages::AppendEntriesRequest,::raft_messages::AppendEntriesResponse>* reactor) override;
      void InstallSnapshot(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::raft_messages::InstallSnapshotRequest,::raft_messages::InstallSnapshotResponse>* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReaderWriter< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>* RequestVoteRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>* AsyncRequestVoteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>* PrepareAsyncRequestVoteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>* AppendEntriesRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>* AsyncAppendEntriesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>* PrepareAsyncAppendEntriesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>* InstallSnapshotRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>* AsyncInstallSnapshotRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>* PrepareAsyncInstallSnapshotRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RequestVote_;
    const ::grpc::internal::RpcMethod rpcmethod_AppendEntries_;
    const ::grpc::internal::RpcMethod rpcmethod_InstallSnapshot_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RequestVote(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::RequestVoteResponse, ::raft_messages::RequestVoteRequest>* stream);
    virtual ::grpc::Status AppendEntries(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::AppendEntriesResponse, ::raft_messages::AppendEntriesRequest>* stream);
    virtual ::grpc::Status InstallSnapshot(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::InstallSnapshotResponse, ::raft_messages::InstallSnapshotRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_RequestVote() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::RequestVoteResponse, ::raft_messages::RequestVoteRequest>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestVote(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::raft_messages::RequestVoteResponse, ::raft_messages::RequestVoteRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_AppendEntries() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::AppendEntriesResponse, ::raft_messages::AppendEntriesRequest>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAppendEntries(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::raft_messages::AppendEntriesResponse, ::raft_messages::AppendEntriesRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::InstallSnapshotResponse, ::raft_messages::InstallSnapshotRequest>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInstallSnapshot(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::raft_messages::InstallSnapshotResponse, ::raft_messages::InstallSnapshotRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(2, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RequestVote<WithAsyncMethod_AppendEntries<WithAsyncMethod_InstallSnapshot<Service > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_RequestVote() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc_impl::internal::CallbackBidiHandler< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>(
          [this] { return this->RequestVote(); }));
    }
    ~ExperimentalWithCallbackMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::RequestVoteResponse, ::raft_messages::RequestVoteRequest>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::experimental::ServerBidiReactor< ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>* RequestVote() {
      return new ::grpc_impl::internal::UnimplementedBidiReactor<
        ::raft_messages::RequestVoteRequest, ::raft_messages::RequestVoteResponse>;}
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_AppendEntries() {
      ::grpc::Service::experimental().MarkMethodCallback(1,
        new ::grpc_impl::internal::CallbackBidiHandler< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>(
          [this] { return this->AppendEntries(); }));
    }
    ~ExperimentalWithCallbackMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::AppendEntriesResponse, ::raft_messages::AppendEntriesRequest>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::experimental::ServerBidiReactor< ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>* AppendEntries() {
      return new ::grpc_impl::internal::UnimplementedBidiReactor<
        ::raft_messages::AppendEntriesRequest, ::raft_messages::AppendEntriesResponse>;}
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_InstallSnapshot() {
      ::grpc::Service::experimental().MarkMethodCallback(2,
        new ::grpc_impl::internal::CallbackBidiHandler< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>(
          [this] { return this->InstallSnapshot(); }));
    }
    ~ExperimentalWithCallbackMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::InstallSnapshotResponse, ::raft_messages::InstallSnapshotRequest>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::experimental::ServerBidiReactor< ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>* InstallSnapshot() {
      return new ::grpc_impl::internal::UnimplementedBidiReactor<
        ::raft_messages::InstallSnapshotRequest, ::raft_messages::InstallSnapshotResponse>;}
  };
  typedef ExperimentalWithCallbackMethod_RequestVote<ExperimentalWithCallbackMethod_AppendEntries<ExperimentalWithCallbackMethod_InstallSnapshot<Service > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_RequestVote() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::RequestVoteResponse, ::raft_messages::RequestVoteRequest>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_AppendEntries() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::AppendEntriesResponse, ::raft_messages::AppendEntriesRequest>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::InstallSnapshotResponse, ::raft_messages::InstallSnapshotRequest>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_RequestVote() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::RequestVoteResponse, ::raft_messages::RequestVoteRequest>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestVote(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_AppendEntries() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::AppendEntriesResponse, ::raft_messages::AppendEntriesRequest>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAppendEntries(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::InstallSnapshotResponse, ::raft_messages::InstallSnapshotRequest>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInstallSnapshot(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(2, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_RequestVote() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc_impl::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this] { return this->RequestVote(); }));
    }
    ~ExperimentalWithRawCallbackMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::RequestVoteResponse, ::raft_messages::RequestVoteRequest>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::experimental::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* RequestVote() {
      return new ::grpc_impl::internal::UnimplementedBidiReactor<
        ::grpc::ByteBuffer, ::grpc::ByteBuffer>;}
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_AppendEntries() {
      ::grpc::Service::experimental().MarkMethodRawCallback(1,
        new ::grpc_impl::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this] { return this->AppendEntries(); }));
    }
    ~ExperimentalWithRawCallbackMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::AppendEntriesResponse, ::raft_messages::AppendEntriesRequest>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::experimental::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* AppendEntries() {
      return new ::grpc_impl::internal::UnimplementedBidiReactor<
        ::grpc::ByteBuffer, ::grpc::ByteBuffer>;}
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_InstallSnapshot() {
      ::grpc::Service::experimental().MarkMethodRawCallback(2,
        new ::grpc_impl::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this] { return this->InstallSnapshot(); }));
    }
    ~ExperimentalWithRawCallbackMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::raft_messages::InstallSnapshotResponse, ::raft_messages::InstallSnapshotRequest>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::experimental::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* InstallSnapshot() {
      return new ::grpc_impl::internal::UnimplementedBidiReactor<
        ::grpc::ByteBuffer, ::grpc::ByteBuffer>;}
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace raft_messages


#endif  // GRPC_raft_5fmessages_2eproto__INCLUDED
